baseURL = "https://zak.ee"
title = "Zakee's Planet"
staticDir = ["static", "content-static"]
languageCode = "zh-CN"
defaultContentLanguage = 'zh'
hasCJKLanguage = true
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "Zakee"

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    noClasses = false

  # [markup.blackFriday]
  #   hrefTargetBlank = true

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 02"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  description = "Zakee的个人博客"
  keywords = "Zakee,Track3,blog,博客,个人网站,中文独立博客"
  accentColor = "#54BAB9"
  images = ["apple-touch-icon.png"]
  # bgImg = "/img/bg.jpg"
  # gitUrl = "https://github.com/Track3/blog/commit/"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/ThatTrack3"

  [[params.social]]
    name = "telegram"
    url = "http://t.me/ThatTrack3"

  [[params.social]]
    name = "github"
    url = "https://github.com/Track3"

[menu]

  [[menu.main]]
    name = "Writing"
    pageref = "/writing"
    weight = 10

  [[menu.main]]
    name = "Gallery"
    pageref = "/gallery"
    weight = 20

  [[menu.main]]
    name = "Link"
    pageref = "/link"
    weight = 30

  [[menu.main]]
    name = "About"
    pageref = "/about"
    weight = 40
