baseURL = "https://zak.ee"
title = "Zakee's Planet"
staticDir = ["static", "content-static"]
languageCode = "zh-CN"
defaultContentLanguage = 'zh'
hasCJKLanguage = true
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[params.author]
  name = "Zakee"

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.goldmark.parser.attribute]
    block = true
    title = true
  [markup.goldmark.extensions.typographer]
    disable = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    noClasses = false

[taxonomies]
  tag = "tags"

[params]
  images = ["apple-touch-icon.png"]

[menu]

  [[menu.main]]
    name = "Home"
    pageref = "/"
    weight = 1
    [menu.main.params]
      description = "主页"

  [[menu.main]]
    name = "Writing"
    pageref = "/writing"
    weight = 10
    [menu.main.params]
      description = "文章归档"

  [[menu.main]]
    name = "Gallery"
    pageref = "/gallery"
    weight = 20
    [menu.main.params]
      description = "相册"

  [[menu.main]]
    name = "Link"
    pageref = "/link"
    weight = 30
    [menu.main.params]
      description = "链接与留言板"

  [[menu.main]]
    name = "About"
    pageref = "/about"
    weight = 40
    [menu.main.params]
      description = "关于"
